---
Resources:
  TUDublinEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: t2.micro
      KeyName: vockey
      ImageId: ami-0dfcb1ef8550277af
  TUDublinS3Bucket12345:
    Type: "AWS::S3::Bucket"
    Properties: {}