---
Parameters:
  AvailabilityZone:
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-2a
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
  ImageId:
    Type: String
    Default: ami-0dfcb1ef8550277af
    AllowedValues:
      - ami-0dfcb1ef8550277af
      - ami-0cc87e5027adcdca8

Resources:
  TUDublinEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId